website/auth.py
""" Module handles sign up and login of user """
from flask import Blueprint, render_template, request, flash, redirect, url_for
import sqlite3
from .views import get_db_connection
from werkzeug.security import generate_password_hash, check_password_hash
from .models import User
from flask_login import login_user, login_required, logout_user, current_user
from . import create_app

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    """ Logins in the user """
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        conn = get_db_connection()
        user = conn.execute('SELECT * FROM users WHERE email = ? LIMIT 1', (email,))
        row = user.fetchone()
        if row is None:
            flash('User does not exist.', category='error')
        else:
            result_dict = dict(zip(row.keys(), row))

            user = User()
            user.id = result_dict['id']
            user.name = result_dict['name']
            user.email = result_dict['email']
            user.contact = result_dict['contact']
            user.password = result_dict['password']
 
            if check_password_hash(result_dict['password'], password):
                login_user(user, remember=True)
                flash('Logged in successfully!', category='success')               
                return redirect(url_for('views.profile'))
            else:
                flash('Incorrect password, try again.', category='error')
        conn.close()
    return render_template("login.html", user=current_user)


    
@auth.route('/logout')
@login_required
def logout():
    """ Logout the user """
    logout_user()
    return redirect(url_for('views.home'))
    
@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    """ sign up method """
    data =request.form
    if request.method == 'POST':
        agency_name = request.form.get('agencyName')
        email = request.form.get('email')
        contact = request.form.get('contact')        
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        # opening a db connenction
        conn = get_db_connection()
        table = conn.execute("SELECT * FROM sqlite_master WHERE type = 'table' AND name LIKE 'users';")
        row = table.fetchone()
        conn.close()
        if row is not None:
            table_dict = dict(zip(row.keys(), row))
            conn = get_db_connection()
            user = conn.execute('SELECT * FROM users WHERE email = ? LIMIT 1', (email,))
            row = user.fetchone()
            if row is not None:
                flash('Email already exists.', category='error')
            else:
                if add_user(agency_name, email, contact, password1, password2):
                    return redirect(url_for('auth.login'))
        else:
            if add_user(agency_name, email, contact, password1, password2):
                return redirect(url_for('auth.login'))
            
    return render_template("sign_up.html")

def add_user(agency_name, email, contact, password1, password2):
    """ Adds the user to the database """
    if len(agency_name) < 2:
        flash('Agency name must be greater than 1 characters.', category='error')
    elif len(email) < 11:
        flash('Agency email must be greater than 10 characters.', category='error')
    elif len(contact) < 9:
        flash('Phone number must be greater than 8 characters.', category='error')
    elif password1 != password2:
        flash('Passwords don\'t match.', category='error')
    elif len(password1) < 8:
        flash('Password must be at least 8 characters.', category='error')
    else:
        password = generate_password_hash(password1, method='scrypt')
        conn = get_db_connection()
        #create users table if not exist
        conn.execute('CREATE TABLE IF NOT EXISTS users ('
            'id INTEGER PRIMARY KEY AUTOINCREMENT,'
            'name STRING(150) UNIQUE,'
            'email STRING(150) UNIQUE,'
            'contact INTEGER UNIQUE,'
            'password STRING(150)'
            ');'
        )
        conn.commit()
        conn.execute('INSERT INTO users (name, email, contact, password) VALUES (?, ?, ?, ?)',
                    (agency_name, email, contact, password))
        conn.commit()

        flash('Account created successfully!', category='success')

        table = conn.execute("SELECT * FROM sqlite_master WHERE type = 'table' AND name='users';")
        row = table.fetchone() is not None
        
        if row:
            #create properties if not exist
            conn.execute('CREATE TABLE IF NOT EXISTS properties ('
            'id INTEGER PRIMARY KEY AUTOINCREMENT,'
            'name STRING(150),'
            'bd INTERGER,'
            'location STRING(150),'
            'price INTEGER,'
            'user_id INTEGER,'
            'FOREIGN KEY (user_id) REFERENCES users (id)'
            ');'
        )
            #create images if not exist
            conn.execute('CREATE TABLE IF NOT EXISTS images ('
            'id INTEGER PRIMARY KEY AUTOINCREMENT,'
            'filename STRING(150),'
            'property_id INTEGER,'
            'FOREIGN KEY (property_id) REFERENCES properties (id) ON DELETE CASCADE'
            ');'
        )
            #create bios if not exist
            conn.execute('CREATE TABLE IF NOT EXISTS bios ('
            'id INTEGER PRIMARY KEY AUTOINCREMENT,'
            'filename STRING(150),'
            'description TEXT,'
            'user_id INTEGER,'
            'FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE'
            ');'
        )
        conn.commit()            
        conn.close()
        return True
    return False

website/views.py
""" Modules holds all the routes """
from flask import Blueprint, render_template, flash, redirect, request, current_app, redirect, url_for, send_from_directory
import sqlite3
from flask_mail import Message, Mail
from flask_login import login_required, current_user
from . import db
import os
from werkzeug.utils import secure_filename

views = Blueprint('views', __name__)

ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'webp'}


def get_db_connection():
    """ Initializes db connection """
    conn = sqlite3.connect('database.db')
    conn.row_factory = sqlite3.Row
    return conn

def allowed_file(filename):
    """ Checks whether the image file type is among the allowed extentions """
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@views.route('/')
def home():
    """ Renders the home page """
    if request.method == "GET":
        conn = get_db_connection()
        properties = conn.execute('SELECT * FROM properties ORDER BY id DESC LIMIT 3').fetchall()
        file_dict = {}
        # Iterate through each row in user_properties
        for row in properties:
            property_id = row['id']

            agency = conn.execute('SELECT name, contact FROM users WHERE id = ?', (row['user_id'],)).fetchone()
            agency_name, contact = agency['name'], agency['contact'] if agency else None
    
            # Retrieve filenames from the images table for the current property_id
            images = conn.execute('SELECT filename FROM images WHERE property_id = ?', (property_id,)).fetchall()
        
            # Extract the filenames from the result set
            filenames = [image['filename'] for image in images]
        
            # Assign the filenames to the property_id in the dictionary
            file_dict[property_id] = {'filenames': filenames, 'agency_name': agency_name, 'contact': contact}
    return render_template("home.html", properties=properties, files=file_dict)

@views.route('/aboutUs')
def aboutUs():
    """ Renders the about page """
    return render_template("about.html")

@views.route('/properties', methods=['GET'])
def properties():
    """ Renders the properties page """
    if request.method == "GET":
        conn = get_db_connection()
        properties = conn.execute('SELECT * FROM properties').fetchall()
        file_dict = {}
        # Iterate through each row in user_properties
        for row in properties:
            property_id = row['id']

            agency = conn.execute('SELECT name, contact FROM users WHERE id = ?', (row['user_id'],)).fetchone()
            agency_name, contact = agency['name'], agency['contact'] if agency else None
    
            # Retrieve filenames from the images table for the current property_id
            images = conn.execute('SELECT filename FROM images WHERE property_id = ?', (property_id,)).fetchall()
        
            # Extract the filenames from the result set
            filenames = [image['filename'] for image in images]
        
            # Assign the filenames to the property_id in the dictionary
            file_dict[property_id] = {'filenames': filenames, 'agency_name': agency_name, 'contact': contact}
        conn.close()
        return render_template("properties.html", properties=properties, files=file_dict)

@views.route('/agents')
def agents():
    """ Renders the agents page """
    conn = get_db_connection()
    query = '''
        SELECT users.id, users.name, users.contact, bios.filename, bios.description
        FROM users
        LEFT JOIN bios ON users.id = bios.user_id
    '''
    agents = conn.execute(query).fetchall()
    conn.close()
    return render_template("agents.html", agents=agents)

@views.route('/agent/<id>')
def agent(id):
    """ Renders the specific agent page """
    conn = get_db_connection()
    agent_properties = conn.execute('SELECT * FROM properties WHERE user_id = ?', (id,)).fetchall()
    agent = conn.execute('SELECT * FROM users WHERE id = ?', (id,)).fetchone()
    file_dict = {}
    # Iterate through each row in user_properties
    for row in agent_properties:
        property_id = row['id']
    
        # Retrieve filenames from the images table for the current property_id
        images = conn.execute('SELECT filename FROM images WHERE property_id = ?', (property_id,)).fetchall()
    
        # Extract the filenames from the result set
        filenames = [image['filename'] for image in images]
    
        # Assign the filenames to the property_id in the dictionary
        file_dict[property_id] = filenames

    conn.close()
    return render_template("agent_properties.html", agent_properties=agent_properties, files=file_dict, agent=agent)

@views.route('/contactUs', methods=['GET', 'POST'])
def contactUs():
    """ Renders the contact page """

    if request.method == 'POST':
        name = request.form['name']
        email = request.form['email']
        phone = request.form['phone']
        subject = request.form['subject']
        message = request.form['message']

        mail = Mail(current_app)
        mail.init_app(current_app)

        msg = Message(
            subject="New contact form submission - {}".format(subject),
            sender="kodyapp@yahoo.com",
            recipients=['transcriberandwriter@gmail.com']
        )

        msg.body = f"Name: {name}\nEmail: {email}\nPhone: {phone}\n\n{message}"

        try:
            mail.send(msg)
            flash('Thank you for your message. We will get back to you shortly.')

        except Exception as e:
            flash('An error occurred while sending the message. Please try again later.')
        return redirect(url_for('views.home'))

    return render_template("contact.html")


@views.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    """ Renders the profile page once user is logged in"""
    if request.method == 'POST':
        description = request.form.get('description')
        conn = get_db_connection()
        desc = conn.execute('SELECT * FROM bios WHERE user_id = ?', (current_user.id,)).fetchone()
        if desc is not None:
                conn.execute('UPDATE bios SET description = ? WHERE user_id = ?', (description, current_user.id))
        else:
            conn.execute(
                'INSERT INTO bios (description, user_id) VALUES (?, ?)',
                (description, current_user.id)
            )
        conn.commit()
        conn.close()
    conn = get_db_connection()
    user_properties = conn.execute('SELECT * FROM properties WHERE user_id = ?', (current_user.id,)).fetchall()
    file_dict = {}
    # Iterate through each row in user_properties
    for row in user_properties:
        property_id = row['id']
    
        # Retrieve filenames from the images table for the current property_id
        images = conn.execute('SELECT filename FROM images WHERE property_id = ?', (property_id,)).fetchall()
    
        # Extract the filenames from the result set
        filenames = [image['filename'] for image in images]
    
        # Assign the filenames to the property_id in the dictionary
        file_dict[property_id] = filenames

    profile_pic = conn.execute('SELECT * FROM bios WHERE user_id = ?', (current_user.id,)).fetchone()
    conn.close()
    return render_template("profile.html", user_properties=user_properties, files=file_dict, pic=profile_pic)

@views.route('/details/edit', methods=['GET', 'POST'])
@login_required
def edit_profile():
    """ Handles profile editing """
    if request.method == "POST":
        agency_name = request.form.get('agencyName')
        email = request.form.get('email')
        contact = request.form.get('contact')   
        conn = get_db_connection()
        conn.execute('UPDATE users SET name = ?, email = ?, contact = ? WHERE id = ?',
              (agency_name, email, contact, current_user.id))
        conn.commit()
        conn.close()

        flash('Profile updated successfully!', category='success')
        return redirect(url_for(".profile"))
    conn = get_db_connection()
    dataobj = conn.execute('SELECT * FROM users WHERE id = ?',
                    (current_user.id,)).fetchone()
    
    data = dict(zip(dataobj.keys(), dataobj))
    conn.commit()
    conn.close()
    return render_template("edit_profile.html", data=data)

@views.route('/profile/create', methods=['GET', 'POST'])
@login_required
def add_properties():
    """ Handles addition of properties page"""
    if request.method == "POST":
        name = request.form.get('propertyName')
        bd = request.form.get('bd')
        location = request.form.get('location')
        price = request.form.get('price')
        conn = get_db_connection()
        created_property = conn.execute('INSERT INTO properties (name, bd, location, price, user_id) VALUES (?, ?, ?, ?, ?)',
                    (name, bd, location, price, current_user.id))
        property_id = created_property.lastrowid
        conn.commit()
        conn.close()

        flash('Property added successfully!', category='success')
        flash('upload property images!', category='request')
        return redirect(url_for("views.upload_image", property_id=property_id))
    return render_template("create_properties.html")


@views.route('/upload/<property_id>', methods=['GET', 'POST'])
def upload_image(property_id):
    """ Handles property's images upload page """
    if request.method == 'POST':
        if 'images[]' not in request.files:
            flash("No image(s) uploaded. Image must be 'png', 'jpg', or 'jpeg'")
        files = request.files.getlist('images[]')

        for file in files:
            if file and allowed_file(file.filename):
                # Save the image to a folder on your server
                filename = secure_filename(file.filename)
                from . import create_app
                app = create_app()
                file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))

website/templates/about.html
{% extends "base.html" %} {% block title %}About-us{% endblock %} {% block
content %}
<section class="about">
  <div>
    <h1>ABOUT US</h1>
  </div>
</section>
<section class="about">
  <div class="about_sec" id="first_sec">
    <div class="column" id="mission">
      <h3>Our Mission:</h3>
      <p class="mbr-text mbr-fonts-style display-4">
        To deliver the best and simplest platform that connects tenants with agents
      </p>
    </div>
    <div class="column" id="about_img">
      <img class="hero-image" src="../static/images/agent_client2.jpg" alt="About Us" />
    </div>
  </div>
</section>
<section class="about">
  <div class="about_sec" id="second_sec">
    <div class="column" id="mission">
      <h3>Our Vision:</h3>
      <p>To trasform lives by revolutionizing Real Estate</p>
    </div>
    <div class="column" id="about_img">
      <img class="hero-image" src="../static/images/agent_client3.jpg" alt="About Us" />
    </div>
  </div>
</section>
<section>
  <h3 class="features-heading">Our Values</h3>
  <div class="my_container">
    <div class="row justify-content-center mt-4">
      <div class="feature col-12 col-md-6 col-lg-4">
        <div class="feature-wrapper">
          <div class="feature-img" style="padding-bottom: 0%">
            <picture>
              <source
                data-srcset="../static/images/Reliable"
                type="../static/image/jpg"
                srcset="../static/images/Reliable.jpg"
              />
              <img
                class="lazyloaded"
                src="../static/images/Reliable.png"
                alt="Agents compete here"
              />
            </picture>
          </div>
          <div class="feature-box">
            <h5 class="feature-title mbr-fonts-style display-5">
              <strong>Reliability</strong>
            </h5>
            <p class="mbr-text mbr-fonts-style display-4">
              "We are willing to go where no one has ever been before, to try
              what no one is trying, and trusting our experience to bear only
              what is best for our clients."
            </p>
          </div>
        </div>
      </div>
      <div class="feature col-12 col-md-6 col-lg-4">
        <div class="feature-wrapper">
          <div class="feature-img" style="padding-bottom: 0%">
            <picture>
              <source
                data-srcset="../static/images/couple.jpeg"
                type="../static/image/jpeg"
                srcset="../static/images/couple.jpeg"
              />
              <img
                class="lazyloaded"
                src="../static/images/couple.jpeg"
                alt="We got you covered"
              />
            </picture>
          </div>
          <div class="feature-box">
            <h5 class="feature-title mbr-fonts-style display-5">
              <strong>Convenience</strong>
            </h5>
            <p class="mbr-text mbr-fonts-style display-4">
              "At KODY, we bring the perfect house to you. Our platform is
              designed to make the process of looking for your new home easier,
              faster, and more efficient."
            </p>
          </div>
        </div>
      </div>
      <div class="feature col-12 col-md-6 col-lg-4">
        <div class="feature-wrapper">
          <div class="feature-img" style="padding-bottom: 0%">
            <picture>
              <source
                data-srcset="../static/images/agents.png"
                type="../static/image/png"
                srcset="../static/images/agents.png"
              />
              <img
                class="lazyloaded"
                src="../static/images/agents.png"
                alt="Agents compete here"
              />
            </picture>
          </div>
          <div class="feature-box">
            <h5 class="feature-title mbr-fonts-style display-5">
              <strong>Efficiency</strong>
            </h5>
            <p class="mbr-text mbr-fonts-style display-4">
              "Kody gives agents a platform to advertise their vacant houses. Our
              platform attracts people from different locations who are looking
              for the best houses and apartments to make them their home. Get a
              renter as soon as you create your listing"
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="column">
    <a href="{{ url_for('views.properties') }}" id="" class="cta-button"
      >View Properties</a
    >
    <a href="{{ url_for('auth.sign_up') }}" class="cta-button"
      >Create your Listing</a
    >
  </div>
</section>
<section class="about">
  <div class="inspiration">
    <h3>Our Inspiration:</h3>
    <p class="mbr-text mbr-fonts-style display-4">
      From our own personal experiences, we know firsthand the arduous and time-consuming process of searching for a new home. The frustrations of unreliable agents and unresponsive websites resonates with us deeply. Determined to rewrite this story, we decided to do build KODY—a platform that transforms the renting experience for our Portifolio Project at ALX.
    </p>
    <p class="mbr-text mbr-fonts-style display-4">
      At KODY, we offer an extensive selection of meticulously curated rental properties. Our experienced agents ensure that you find the ideal home that suits your needs and preferences. With instant access to detailed property listings, including high-quality images, comprehensive descriptions, pricing, and availability, you can make informed decisions.
    </p>
    <p class="mbr-text mbr-fonts-style display-4">
      Direct communication is key, and KODY facilitates it effortlessly. Connect directly with agents representing the properties you're interested in, enabling you to ask questions, schedule viewings, and receive timely responses.
    </p>      
    <p class="mbr-text mbr-fonts-style display-4">
      Rest easy knowing that KODY prioritizes your security and peace of mind. All agents and properties on our platform are verified and vetted, ensuring a trustworthy and safe rental experience.
    </p>
    <p class="mbr-text mbr-fonts-style display-4">
      Agents, look no further! KODY is here to revolutionize your renting experience. Our user-friendly interface and extensive network provide the ultimate platform to register and showcase your available rental houses.
    </p>
    <p class="mbr-text mbr-fonts-style display-4">    
      Welcome to KODY, where we rewrite the story of renting and bring joy and efficiency to your search.
    </p>
  </div>
</section>
<section class="about">
  <div>
    <h3>Our Team:</h3>
  </div>
</section>
<section class="about">
  <div class="about_sec" id="team">
    <div class="column" id="mission">
      <h3>Winfred Kiarie</h3>
      <br>
      <p class="mbr-text mbr-fonts-style display-4">
        <a href="https://www.linkedin.com/in/winfred-kiarie/">LinkedIn</a>
      </p>
      <p class="mbr-text mbr-fonts-style display-4">
        <a href="https://github.com/epicsociety">Github</a>
      </p>
    </div>
    <div class="column" id="mission">
      <h3>Prisca Ndiritu</h3>
      <br>
      <p class="mbr-text mbr-fonts-style display-4">
        <a href="https://www.linkedin.com/in/prisca-ndiritu-095515131/">LinkedIn</a>
      </p>
      <p class="mbr-text mbr-fonts-style display-4">
        <a href="https://github.com/ndiritu-prisca">Github</a>
      </p>
    </div>
</section>
<section class="about">
  <div class="repo">
    <h3>Project Repository: <a href="https://github.com/ndiritu-prisca/KODY">KODY</a></h3>
  </div>
</section>
{% endblock %}

website/templates/agent_properties.html
{% extends 'base.html' %} {% block title %} {{ agent.name }} {% endblock %} {%
block content %}
<h1>{{ agent.name }}</h1>
<h3>Phone no.: 0{{ agent.contact }}</h3>

<section class="properties-section">
  <h2>Properties Listed:</h2>
  <div class="row">
    {% for property in agent_properties %} {% if loop.index0 % 3 == 0 and not
    loop.first %}
  </div>
  <div class="row">
    {% endif %}
    <div class="col-md-4">
      <div class="property-section">
        <!-- Retrieve the images for the current property -->
        {% set property_images = files[property.id] %}

        <!-- Display property images in a carousel -->
        <div class="property-carousel">
          <div
            id="carousel-{{ property.id }}"
            class="carousel slide"
            data-ride="carousel"
          >
            <ol class="carousel-indicators">
              {% for image in property_images %}
              <li
                data-target="#carousel-{{ property.id }}"
                data-slide-to="{{ loop.index0 }}"
                {%
                if
                loop.first
                %}class="active"
                {%
                endif
                %}
              ></li>
              {% endfor %}
            </ol>
            <div class="carousel-inner">
              {% for image in property_images %}
              <div class="carousel-item {% if loop.first %}active{% endif %}">
                <img src="../static/uploads/{{ image }}" alt="Property Image" />
              </div>
              {% endfor %}
            </div>
            <a
              class="carousel-control-prev"
              href="#carousel-{{ property.id }}"
              role="button"
              data-slide="prev"
            >
              <span
                class="carousel-control-prev-icon"
                aria-hidden="true"
              ></span>
              <span class="sr-only">Previous</span>
            </a>
            <a
              class="carousel-control-next"
              href="#carousel-{{ property.id }}"
              role="button"
              data-slide="next"
            >
              <span
                class="carousel-control-next-icon"
                aria-hidden="true"
              ></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        </div>

        <!-- Display property details -->
        <div class="property-details">
          <h3>{{ property.bd }} Bedroom(s) at {{ property.name }}</h3>
          <p>Location: {{ property.location }}</p>
          <p>Ksh.{{ property.price }} per month</p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</section>

{% endblock %}

website/templates/agents.html
{% extends 'base.html' %} {% block title %}Our Agents{% endblock %} {% block
  content %}
  <section>
    <div class="top">
      <h2>Our Agencies:</h2>
      <input type="text" placeholder="Search.." id="search-input" />
    </div>
    <div class="agent-sections">
      <div class="agent-row">
        {% set counter = 0 %} {% for agent in agents %} {% if counter % 3 == 0 and
        not loop.first %}
      </div>
      <div class="agent-row">
        {% endif %}
        <div class="agent-details">
          <h3><a href="/agent/{{ agent.id }}">{{ agent.name }}</a></h3>
          <img
            src="../static/uploads/{{ agent.filename }}"
            alt="Profile Picture"
          />
          <p>Contact: {{ agent.contact }}</p>
          <p>Description: {{ agent.description }}</p>
        </div>
        {% set counter = counter + 1 %} {% endfor %}
      </div>
    </div>
  </section>
  {% endblock %}

website/templates/contact.html
{% extends "base.html" %} {% block title %}Contact Us{% endblock %} {% block
content %} {% with messages = get_flashed_messages() %} {% if messages %}
<div class="alert alert-success alert-dismissible">
  {{ messages[0] }}
  <button type="button" class="close" data-dismiss="alert">&times;</button>
</div>
{% endif %} {% endwith %}

<div class="contact-container">
  <div class="wrapper">
    <div class="title">
      <h1>contact us form</h1>
    </div>
    <div class="contact-form">
      <form action="{{ url_for('views.contactUs') }}" method="POST">
        <div class="input-fields">
          <input
            type="text"
            class="input"
            placeholder="Name"
            name="name"
            value="{{ request.form['name'] }}"
          />
          <input
            type="text"
            class="input"
            placeholder="Email Address"
            name="email"
            value="{{ request.form['email'] }}"
          />
          <input
            type="text"
            class="input"
            placeholder="Phone"
            name="phone"
            value="{{ request.form['phone'] }}"
          />
          <input
            type="text"
            class="input"
            placeholder="Subject"
            name="subject"
            value="{{ request.form['subject'] }}"
          />
        </div>
        <div class="msg">
          <textarea
            placeholder="Message"
            name="message"
            value="{{ request.form['message'] }}"
          ></textarea>
          <button type="submit" class="cta-button">Send</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %} {% block footer %}
<footer class="footer">
  <!-- Footer content -->
</footer>
{% endblock %}

website/templates/create_properties.html
{% extends 'base.html' %} {% block content %}
<section class="edit">
  <div class="container">
    <h2>Add a Property</h2>
    <form method="POST">
      <label for="propertyName">Property Name:</label>
      <input type="text" name="propertyName" id="propertyName" required />
      <br />
      <label for="bd">Bedroom(s):</label>
      <input type="number" name="bd" id="bd" required />
      <br />
      <label for="location">Location:</label>
      <input type="text" name="location" id="location" required />
      <br />
      <label for="price">Price:</label>
      <input type="number" name="price" id="price" required />
      <br />
      <input type="submit" value="Add Property" class="submit-button" />
    </form>
  </div>
</section>
{% endblock %}

website/templates/edit_profile.html
{% extends 'base.html' %} {% block title %}Edit Profile{% endblock %} {% block
content %}

<section class="edit">
  <div class="container">
    <h2>Profile Details</h2>
    <form method="POST">
      <label for="agencyName">Agency Name:</label>
      <input
        type="text"
        name="agencyName"
        id="agencyName"
        value="{{ data.name }}"
        required
      />
      <br />
      <label for="email">Email:</label>
      <input
        type="text"
        name="email"
        id="email"
        value="{{ data.email}}"
        required
      />
      <br />
      <label for="contact">Contact:</label>
      <input
        type="number"
        name="contact"
        id="contact"
        value="{{ data.contact }}"
        required
      />
      <br />
      <input type="submit" value="Update Profile" class="submit-button" />
    </form>
  </div>
</section>
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<div class="login_con">
  <form method="POST">
    <div class="box">
      <div class="login_container">
        <div class="top-header">
          <h2>Login</h2>
        </div>
        <div class="input-field">
          <input
            type="email"
            class="input"
            id="email"
            name="email"
            placeholder="Enter agency email"
          />
        </div>

        <div class="input-field">
          <input
            type="password"
            class="input"
            id="password"
            name="password"
            placeholder="Enter password"
          />
        </div>

        <div class="input-field">
          <input type="submit" class="submit" value="Login" />
        </div>
      </div>
    </div>
  </form>
</div>
{% endblock %}